# Labeler configuration
# See: https://github.com/actions/labeler
# Labels must match those defined in .github/maintenance/labels.sh

# Documentation areas
area/docs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.md"
          - "**/*.mdx"

# CI/CD
area/ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"

# Architecture documentation
area/architecture:
  - changed-files:
      - any-glob-to-any-file:
          - "**/architecture/**/*"
          - "**/design/**/*"

# RFCs
area/rfcs:
  - changed-files:
      - any-glob-to-any-file:
          - "**/rfcs/**/*"
          - "**/rfc/**/*"

# Whitepapers
area/whitepapers:
  - changed-files:
      - any-glob-to-any-file:
          - "**/whitepapers/**/*"
          - "**/whitepaper/**/*"

# Deployment documentation (now in deploy repo)
# area/deployment label no longer used - deployment docs moved to inferadb/deploy

# API documentation
area/api:
  - changed-files:
      - any-glob-to-any-file:
          - "**/api/**/*"
          - "**/openapi/**/*"
          - "**/swagger/**/*"

# Security documentation
area/security:
  - changed-files:
      - any-glob-to-any-file:
          - "**/security/**/*"
          - "**/auth/**/*"
          - "**/authentication/**/*"
          - "**/authorization/**/*"

# Guides and tutorials
area/guides:
  - changed-files:
      - any-glob-to-any-file:
          - "**/guides/**/*"
          - "**/tutorials/**/*"
          - "**/quickstart/**/*"
          - "**/getting-started/**/*"

# Configuration
area/config:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.toml"
          - "**/*.yaml"
          - "**/*.yml"
          - "**/*.json"
          - "!.github/**/*"
